# Generated by Django 3.2.9 on 2021-12-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='ip',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='remote_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
