# Generated by Django 3.2.4 on 2021-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_2', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('publicationyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('commercialdataid', models.IntegerField(db_column='commercialDataId', unique=True)),
                ('id_name', models.TextField(blank=True, null=True)),
                ('micrositename', models.TextField(blank=True, db_column='micrositeName', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zip', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('web', models.TextField(blank=True, null=True)),
                ('since_year', models.IntegerField(blank=True, null=True)),
                ('n_total_properties', models.IntegerField(blank=True, null=True)),
                ('n_rent_homes', models.IntegerField(blank=True, null=True)),
                ('n_sale_homes', models.IntegerField(blank=True, null=True)),
                ('epoc_time', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('datetime_stamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('usedlocationid', models.CharField(blank=True, db_column='usedLocationId', max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('subitems_data_location_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('subitems_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
