# Generated by Django 3.2.4 on 2021-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_realtors_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtors_2',
        ),
    ]
