# Generated by Django 3.2.4 on 2021-06-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_realtors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtors',
        ),
    ]
