# Generated by Django 3.2.4 on 2021-06-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_realtors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realtors',
            table='realtors_new',
        ),
    ]
