# Generated by Django 3.2.4 on 2021-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_realtors_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='id',
        ),
        migrations.AlterField(
            model_name='realtors',
            name='commercialdataid',
            field=models.IntegerField(db_column='commercialDataId', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='realtors',
            table='realtors_django',
        ),
    ]
