# Generated by Django 3.2.4 on 2021-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210620_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtors',
            old_name='epoc_time',
            new_name='epoc_date_insert',
        ),
        migrations.AddField(
            model_name='realtors',
            name='epoc_date_update',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtors',
            name='epoc_datetime_stamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
