# Generated by Django 3.2.4 on 2021-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210620_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIKEY', models.CharField(max_length=255)),
                ('zipcode', models.TextField()),
                ('order', models.CharField(max_length=10)),
                ('sort', models.CharField(max_length=4)),
                ('error_reason', models.IntegerField()),
                ('is_valid', models.BooleanField()),
                ('missing_parameters', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
