# Generated by Django 3.2.4 on 2021-06-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210620_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtors',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
