# Generated by Django 3.2.4 on 2021-12-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_realtors_detail_realtors_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorsList',
            fields=[
                ('commercialdataid', models.AutoField(db_column='commercialDataId', primary_key=True, serialize=False)),
                ('id_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('since_year', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True)),
                ('date_insert_epoc', models.IntegerField(blank=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_update_epoc', models.IntegerField(blank=True, null=True)),
                ('url_href', models.CharField(blank=True, max_length=200, null=True)),
                ('url_source', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('success', models.IntegerField()),
                ('active', models.IntegerField(blank=True, null=True)),
                ('karma', models.IntegerField(blank=True, null=True)),
                ('member', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'realtors_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RealtorInputModel',
        ),
        migrations.DeleteModel(
            name='Realtors',
        ),
        migrations.DeleteModel(
            name='Realtors_detail',
        ),
        migrations.DeleteModel(
            name='Realtors_list',
        ),
        migrations.CreateModel(
            name='RealtorDetails',
            fields=[
                ('commercialdataid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.realtorslist')),
                ('id_name', models.CharField(blank=True, max_length=200, null=True)),
                ('micrositename', models.CharField(blank=True, db_column='micrositeName', max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('web', models.CharField(blank=True, max_length=1000, null=True)),
                ('since_year', models.IntegerField(blank=True, null=True)),
                ('n_total_properties', models.IntegerField(blank=True, null=True)),
                ('n_sale_homes', models.IntegerField(blank=True, null=True)),
                ('n_rent_homes', models.IntegerField(blank=True, null=True)),
                ('date_insert', models.DateTimeField(auto_now_add=True)),
                ('date_insert_epoc', models.IntegerField(blank=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_update_epoc', models.IntegerField(blank=True, null=True)),
                ('datetime_stamp', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('url_es_rent', models.CharField(blank=True, max_length=200, null=True)),
                ('usedlocationid', models.CharField(blank=True, db_column='usedLocationId', max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
                ('subitems_data_location_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('subitems_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_batch_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_source', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('success', models.IntegerField()),
                ('active', models.IntegerField(blank=True, null=True)),
                ('zipcode_bis', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=150, null=True)),
                ('karma', models.IntegerField(blank=True, null=True)),
                ('trademark', models.JSONField(blank=True, null=True)),
                ('properties_recent_top_rent_homes', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'realtors_detail',
                'managed': False,
            },
        ),
    ]
